<?php

/**
 * Hindi (hi) direct transliteration mappings for common words.
 */

return [
	// The initial seed for this list of preferred Hindi transliterations was adapted from
	// a subset of the file hi/lexicons/hi.translit.sampled.train.tsv in the Dakshina
	// dataset. The file is a large (>50K entries) many-to-many mapping of Hindi and Latin
	// transliterations (including numerous English words).
	//
	// [The Dakshina Dataset](https://github.com/google-research-datasets/dakshina) is
	// licensed under CC BY-SA 4.0. The paper describing the dataset in more detail is
	// [Processing South Asian Languages Written in the Latin Script: the Dakshina
	// Dataset](https://aclanthology.org/2020.lrec-1.294/) (Roark et al., LREC 2020)
	//
	// This dataset in this file is a many-to-one Latin-to-Hindi mapping of
	// probabilistically preferred transliterations of a much smaller (~1400 entries) set
	// of Latin words. The words included here are the most common words in the Latin
	// alphabet (including Hindi and English) found in a sample of Hindi Wikipedia
	// queries, along with the addition of a few related words (e.g., the rest of the
	// Hindi and English numbers less than twelve). Preferred transliterations for words
	// not in the Dakshina file were sourced from Hindi Wikipedia. Some changes were made
	// to the transliterations from the Dakshina dataset, including minor typographic
	// errors (such as duplicated diacritics  े,  ै, or  ं; or using आ +  ॅ instead of ऑ,
	// or  ा +  ॅ instead of  ॉ), and replacing Hindi words that did not occur more than a
	// handful of times in Hindi Wikipedia with more common candidates.
	//
	// The dataset in this file is licensed under CC BY-SA 4.0, and is provided "As Is"
	// without any warranty, express or implied.

	// Hindi numbers
	'shoonya' => 'शून्य', 'shoony' => 'शून्य', 'shuny' => 'शून्य', 'shunya' => 'शून्य',
	'shuunya' => 'शून्य', 'ek' => 'एक', 'do' => 'दो', 'teen' => 'तीन', 'tin' => 'तीन',
	'char' => 'चार', 'panch' => 'पांच', 'paanch' => 'पांच', 'chah' => 'छह',
	'cheh' => 'छह', 'chhah' => 'छह', 'saat' => 'सात', 'sat' => 'सात', 'ath' => 'आठ',
	'aath' => 'आठ', 'nau' => 'नौ', 'dus' => 'दस', 'das' => 'दस', 'gyaarah' => 'ग्यारह',
	'gyarah' => 'ग्यारह', 'baarah' => 'बारह', 'barah' => 'बारह',

	// English numbers
	'zero' => 'ज़ीरो', 'one' => 'वन', 'two' => 'टू', 'three' => 'थ्री', 'four' => 'फ़ॉर',
	'five' => 'फाइव', 'six' => 'सिक्स', 'seven' => 'सेवन', 'eight' => 'एट',
	'nine' => 'नाइन', 'ten' => 'टेन', 'eleven' => 'इलेवन', 'twelve' => 'ट्वेल्व',

	// most common words
	'aacharya' => 'आचार्य', 'aadhunik' => 'आधुनिक', 'aaj' => 'आज', 'aandolan' => 'आंदोलन',
	'aane' => 'आने', 'aap' => 'आप', 'aata' => 'आता', 'aate' => 'आटे', 'aati' => 'आती',
	'aaya' => 'आया', 'aaye' => 'आये', 'aayog' => 'आयोग', 'ab' => 'एबी',
	'abdul' => 'अब्दुल', 'abhi' => 'अभी', 'about' => 'अबाउट', 'acharya' => 'आचार्य',
	'act' => 'एक्ट', 'actor' => 'एक्टर', 'adani' => 'अदानी', 'adhigam' => 'अधिगम',
	'adhikar' => 'अधिकार', 'adhiniyam' => 'अधिनियम', 'aditya' => 'आदित्य',
	'affairs' => 'अफेयर्स', 'africa' => 'अफ्रीका', 'age' => 'एज', 'agra' => 'आगरा',
	'agrawal' => 'अग्रवाल', 'ai' => 'एआई', 'aids' => 'एड्स', 'air' => 'एअर',
	'airport' => 'एयरपोर्ट', 'ajay' => 'अजय', 'ajit' => 'अजीत', 'ajmer' => 'अजमेर',
	'akbar' => 'अकबर', 'akshay' => 'अक्षय', 'ali' => 'एली', 'all' => 'ऑल',
	'alok' => 'आलोक', 'alwar' => 'अलवर', 'ambedkar' => 'अंबेडकर', 'america' => 'अमेरिका',
	'american' => 'अमेरिकन', 'amir' => 'अमीर', 'amit' => 'अमिट', 'amitabh' => 'अमिताभ',
	'an' => 'अं', 'anand' => 'आनंद', 'and' => 'एंड', 'anderson' => 'एंडरसन',
	'andolan' => 'आंदोलन', 'anil' => 'अनिल', 'ansari' => 'अंसारी', 'answer' => 'आंसर',
	'antar' => 'अंतर', 'antim' => 'अंतिम', 'anuched' => 'अनुच्छेद',
	'anusandhan' => 'अनुसंधान', 'anusar' => 'अनुसर', 'any' => 'एनी', 'apne' => 'अपने',
	'app' => 'ऐप', 'apple' => 'एप्पल', 'application' => 'एप्लीकेशन', 'are' => 'अरे',
	'area' => 'एरिया', 'arjun' => 'अर्जुन', 'army' => 'आर्मी', 'art' => 'आर्ट',
	'arth' => 'अर्थ', 'artical' => 'आर्टिकल', 'article' => 'आर्टिकल', 'arun' => 'अरूण',
	'as' => 'अस', 'ashok' => 'अशोक', 'asia' => 'एशिया', 'assembly' => 'असेंबली',
	'assignment' => 'असाइनमेंट', 'at' => 'एट', 'atal' => 'अटल', 'attack' => 'अटैक',
	'aur' => 'और', 'avam' => 'एवम्', 'avdharna' => 'अवधारणा', 'avm' => 'एवम्',
	'avn' => 'एवं', 'award' => 'अवार्ड', 'ayodhya' => 'अयोध्या', 'azad' => 'आजाद',
	'b' => 'बी', 'ba' => 'बीए', 'baad' => 'बाड़', 'baal' => 'बाल', 'baar' => 'बार',
	'baare' => 'बारे', 'baat' => 'बात', 'baba' => 'बाबा', 'babar' => 'बाबर',
	'babu' => 'बाबू', 'baby' => 'बेबी', 'bacche' => 'बच्चे', 'bache' => 'बचे',
	'bachpan' => 'बचपन', 'bad' => 'बाद', 'bada' => 'बड़ा', 'badi' => 'बड़ी',
	'bag' => 'बैग', 'bagh' => 'बाघ', 'bahadur' => 'बहादुर', 'bahan' => 'बहन',
	'bai' => 'बै', 'bal' => 'बल', 'balaji' => 'बालाजी', 'bali' => 'बलि', 'ban' => 'बन',
	'bana' => 'बाना', 'banane' => 'बनाने', 'banaya' => 'बनाया', 'band' => 'बंद',
	'bandh' => 'बंध', 'bane' => 'बाने', 'bangal' => 'बंगाल', 'bangladesh' => 'बांग्लादेश',
	'bani' => 'बानी', 'bank' => 'बैंक', 'banta' => 'बांटा', 'bar' => 'बार',
	'bare' => 'बारे', 'bataen' => 'बताएं', 'bataiye' => 'बताईए', 'batao' => 'बताओ',
	'bataye' => 'बताये', 'bazar' => 'बजार', 'begusarai' => 'बेगूसराय',
	'bengal' => 'बंगाल', 'best' => 'बेस्ट', 'beti' => 'बेटी', 'between' => 'बिटवीन',
	'bf' => 'बीएफ', 'bhabhi' => 'भाभी', 'bhag' => 'भाग', 'bhagat' => 'भगत',
	'bhagwan' => 'भगवान', 'bhagwat' => 'भगवत', 'bhai' => 'भाई', 'bhairav' => 'भैरव',
	'bhakti' => 'भक्ति', 'bhandari' => 'भंडारी', 'bharat' => 'भारत', 'bhart' => 'भारत',
	'bharti' => 'भर्ती', 'bhartiy' => 'भारतीय', 'bhartiya' => 'भारतीय',
	'bhartiye' => 'भारतीय', 'bhasa' => 'भासा', 'bhasha' => 'भाषा', 'bhatt' => 'भट्ट',
	'bhav' => 'भाव', 'bhi' => 'भी', 'bhim' => 'भीम', 'bhimrao' => 'भीमराव',
	'bhojpuri' => 'भोजपुरी', 'bhopal' => 'भोपाल', 'bhu' => 'भू', 'bhumi' => 'भूमि',
	'bhumika' => 'भूमिका', 'bich' => 'बीच', 'bidhan' => 'बिधान', 'big' => 'बिग',
	'bihar' => 'बिहार', 'bihari' => 'बिहारी', 'bin' => 'बिन', 'bina' => 'बिना',
	'biography' => 'बायोग्राफी', 'bird' => 'बर्ड', 'birsa' => 'बिरसा', 'birth' => 'बिरथ',
	'bjp' => 'बीजेपी', 'block' => 'ब्लॉक', 'bna' => 'बना', 'board' => 'बोर्ड',
	'body' => 'बॉडी', 'bola' => 'बोला', 'bollywood' => 'बॉलीवुड', 'book' => 'बुक',
	'books' => 'बुक्स', 'border' => 'बॉर्डर', 'bose' => 'बोस', 'boss' => 'बॉस',
	'boy' => 'बॉय', 'br' => 'बीआर', 'brahman' => 'ब्राह्मण', 'bridge' => 'ब्रिज',
	'bsc' => 'बीएससी', 'btao' => 'बताओ', 'buddha' => 'बुड्ढा', 'budget' => 'बजट',
	'budh' => 'बुध', 'bus' => 'बस', 'business' => 'बिजनेस', 'by' => 'बी', 'call' => 'कॉल',
	'cap' => 'कैप', 'capital' => 'कैपिटल', 'captain' => 'कैप्टन', 'car' => 'कार',
	'card' => 'कार्ड', 'case' => 'कैसे', 'cast' => 'कास्ट', 'caste' => 'कासते',
	'cat' => 'कैट', 'cell' => 'सेल', 'cg' => 'सीजी', 'chahie' => 'चहिए',
	'chahiye' => 'चहिए', 'chakra' => 'चक्र', 'champaran' => 'चंपारण',
	'championship' => 'चैंपियनशिप', 'chand' => 'चांद', 'chanda' => 'चंदा',
	'chandan' => 'चंदन', 'chandra' => 'चंद्र', 'chapter' => 'चैप्टर', 'charan' => 'चरण',
	'charcha' => 'चर्चा', 'chart' => 'चार्ट', 'chat' => 'चैट', 'chauhan' => 'चौहान',
	'chemical' => 'केमिकल', 'chemistry' => 'केमिस्ट्री', 'chetra' => 'चैत्र',
	'chhattisgarh' => 'छत्तीसगढ़', 'chief' => 'चीफ', 'chin' => 'चीन', 'china' => 'चाइना',
	'chinh' => 'चिन्ह', 'chirag' => 'चिराग', 'chitra' => 'चित्रा', 'choudhary' => 'चौधरी',
	'chudai' => 'चुदाई', 'chunav' => 'चुनाव', 'chunaw' => 'चुनाव', 'city' => 'सिटी',
	'class' => 'क्लास', 'cm' => 'कम', 'code' => 'कोड', 'collection' => 'कलेक्शन',
	'college' => 'कॉलेज', 'colour' => 'कलर', 'com' => 'कॉम',
	'communication' => 'कम्युनिकेशन', 'company' => 'कंपनी', 'computer' => 'कंप्यूटर',
	'congress' => 'कांग्रेस', 'country' => 'कंट्री', 'course' => 'कोर्स',
	'court' => 'कोर्ट', 'cricket' => 'क्रिकेट', 'cricketer' => 'क्रिकेटर',
	'cricketing' => 'क्रिकेटिंग', 'crime' => 'क्राइम', 'culture' => 'कल्चर',
	'cup' => 'कप', 'currency' => 'करेंसी', 'cut' => 'कट', 'd' => 'ड', 'dada' => 'दादा',
	'dakait' => 'डकैत', 'dal' => 'डाल', 'daliye' => 'दलीय', 'dam' => 'डैम',
	'damini' => 'दामिनी', 'dance' => 'डांस', 'dangerous' => 'डेंजरस', 'dark' => 'डार्क',
	'darshan' => 'दर्शन', 'data' => 'डाटा', 'date' => 'डेट', 'day' => 'डे', 'de' => 'दे',
	'death' => 'डेथ', 'december' => 'दिसंबर', 'deep' => 'डीप', 'deepak' => 'दीपक',
	'definition' => 'डेफिनेशन', 'dehradun' => 'देहरादून', 'delhi' => 'दिल्ली',
	'deol' => 'देओल', 'desh' => 'देश', 'desi' => 'देसी', 'deta' => 'देता',
	'details' => 'डिटेल्स', 'dev' => 'देव', 'development' => 'डेवलपमेंट',
	'devi' => 'देवी', 'devta' => 'देवता', 'dham' => 'धम', 'dhan' => 'धन',
	'dhara' => 'धरा', 'dharam' => 'धरम', 'dharm' => 'धर्म', 'dharmendra' => 'धर्मेंद्र',
	'dhatu' => 'धातु', 'dhurandhar' => 'धुरंधर', 'di' => 'दि', 'difference' => 'डिफरेंट',
	'digital' => 'डिजिटल', 'dijiye' => 'दीजिए', 'dikhaiye' => 'दिखाइए', 'dil' => 'दिल',
	'diljale' => 'दिलजले', 'din' => 'दिन', 'dinkar' => 'दिनकर',
	'district' => 'डिस्ट्रिक्ट', 'divas' => 'दिवस', 'diwas' => 'दिवस', 'diya' => 'दिया',
	'dj' => 'डीजे', 'doctor' => 'डॉक्टर', 'dog' => 'डॉग', 'download' => 'डाउनलोड',
	'dukhi' => 'दुखी', 'duniya' => 'दुनिया', 'dur' => 'दूर', 'durga' => 'दुर्गा',
	'dwara' => 'द्वारा', 'e' => 'इ', 'earth' => 'एअर्थ', 'east' => 'ईस्ट',
	'economic' => 'इकोनॉमिक', 'economics' => 'इकनॉमिक्स', 'education' => 'एजुकेशन',
	'election' => 'इलेक्शन', 'email' => 'ईमेल', 'empire' => 'अंपायर', 'en' => 'ऐं',
	'england' => 'इंग्लैंड', 'english' => 'इंग्लिश', 'episode' => 'एपिसोड',
	'essay' => 'एसे', 'exam' => 'एग्जाम', 'explain' => 'एक्सप्लेन', 'facts' => 'फैक्ट्स',
	'family' => 'फैमिली', 'famous' => 'फेमस', 'father' => 'फादर', 'fayde' => 'फायदे',
	'fighter' => 'फाइटर', 'file' => 'फाइल', 'film' => 'फिल्म', 'fire' => 'फायर',
	'first' => 'फर्स्ट', 'food' => 'फुड', 'for' => 'फॉर', 'force' => 'फोर्स',
	'form' => 'फॉर्म', 'formula' => 'फार्मूला', 'fort' => 'फोर्ट', 'free' => 'फ्री',
	'freedom' => 'फ्रीडम', 'from' => 'फ्रॉम', 'full' => 'फुल', 'gai' => 'गई',
	'game' => 'गेम', 'games' => 'गेम्स', 'gana' => 'गाना', 'gandhi' => 'गांधी',
	'gandi' => 'गंदी', 'ganesh' => 'गणेश', 'ganga' => 'गंगा', 'gaon' => 'गांव',
	'gas' => 'गैस', 'gaurav' => 'गौरव', 'gautam' => 'गौतम', 'gav' => 'गांव',
	'gaya' => 'गया', 'gaye' => 'गाये', 'gdp' => 'जीडीपी', 'geet' => 'गीत',
	'geeta' => 'गीता', 'general' => 'जनरल', 'geography' => 'जियोग्राफी', 'ghar' => 'घर',
	'ghat' => 'घाट', 'ghati' => 'घटी', 'ginti' => 'गिनती', 'girl' => 'गर्ल',
	'gita' => 'गीता', 'gk' => 'जीके', 'goa' => 'गोवा', 'god' => 'गोद', 'gold' => 'गोल्ड',
	'good' => 'गुड', 'google' => 'गूगल', 'gotra' => 'गोत्र', 'government' => 'गवर्नमेंट',
	'govind' => 'गोविंद', 'gram' => 'ग्राम', 'great' => 'ग्रेट', 'green' => 'ग्रीन',
	'group' => 'ग्रुप', 'gujarati' => 'गुजराती', 'gun' => 'गुण', 'gundosh' => 'गुणदोष',
	'gupt' => 'गुप्त', 'gupta' => 'गुप्ता', 'gurjar' => 'गुर्जर', 'guru' => 'गुरु',
	'gwalior' => 'ग्वालियर', 'gya' => 'गया', 'gyan' => 'ज्ञान', 'h' => 'एच', 'ha' => 'ह',
	'hai' => 'है', 'hain' => 'हैं', 'hanuman' => 'हनुमान', 'har' => 'हर', 'hare' => 'हरे',
	'hari' => 'हरि', 'harsh' => 'हर्ष', 'haryana' => 'हरियाणा', 'hath' => 'हठ',
	'hatya' => 'हत्या', 'he' => 'हे', 'heart' => 'हार्ट', 'help' => 'हेल्प',
	'helper' => 'हेल्पर', 'hema' => 'हेमा', 'hero' => 'हीरो', 'hetu' => 'हेतु',
	'hi' => 'हि', 'high' => 'हाई', 'hind' => 'हिंद', 'hindi' => 'हिंदी',
	'hindu' => 'हिंदु', 'hindustan' => 'हिंदुस्तान', 'his' => 'हिज',
	'history' => 'हिस्ट्री', 'ho' => 'हो', 'hoga' => 'होगा', 'hold' => 'होल्ड',
	'holder' => 'होल्डर', 'home' => 'होम', 'hone' => 'होने', 'hospital' => 'हॉस्पिटल',
	'hot' => 'हॉट', 'hota' => 'होता', 'hote' => 'होते', 'hotel' => 'होटल',
	'hoti' => 'होती', 'house' => 'हाउस', 'how' => 'हाउ', 'hu' => 'हु', 'hua' => 'हुआ',
	'huaa' => 'हुआ', 'hue' => 'हुए', 'hui' => 'हुई', 'human' => 'ह्यूमन',
	'husband' => 'हसबैंड', 'hussain' => 'हुसैन', 'huye' => 'हुए', 'ibrahim' => 'इब्राहिम',
	'icc' => 'आईसीसी', 'id' => 'आईडी', 'image' => 'इमेज', 'in' => 'इन',
	'india' => 'इंडिया', 'indian' => 'इंडियन', 'indira' => 'इंदिरा', 'indore' => 'इंदौर',
	'indra' => 'इंद्र', 'information' => 'इन्फॉर्मेशन', 'international' => 'इंटरनेशनल',
	'ipad' => 'आईपैड', 'is' => 'इस', 'ishq' => 'इश्क', 'iska' => 'इसका', 'iske' => 'इसके',
	'islam' => 'इस्लाम', 'it' => 'आईटी', 'itihaas' => 'इतिहास', 'itihas' => 'इतिहास',
	'ja' => 'जा', 'jaane' => 'जाने', 'jaat' => 'जाट', 'jaati' => 'जाति',
	'jabalpur' => 'जबलपुर', 'jada' => 'जड़ा', 'jagah' => 'जगह', 'jagannath' => 'जगन्नाथ',
	'jai' => 'जय', 'jail' => 'जेल', 'jain' => 'जैन', 'jaipur' => 'जयपुर', 'jal' => 'जल',
	'jamin' => 'जमीन', 'jammu' => 'जम्मू', 'jan' => 'जन', 'jana' => 'जाना',
	'janam' => 'जन्म', 'jane' => 'जने', 'janjati' => 'जनजाति', 'jankari' => 'जानकारी',
	'janm' => 'जन्म', 'jansankhya' => 'जनसंख्या', 'janta' => 'जनता', 'japan' => 'जापान',
	'jat' => 'जाट', 'jata' => 'जाता', 'jate' => 'जाते', 'jati' => 'जाति',
	'jawaharlal' => 'जवाहरलाल', 'jay' => 'जय', 'jayanti' => 'जयंती', 'jeevan' => 'जीवन',
	'jeewan' => 'जीवन', 'jharkhand' => 'झारखंड', 'ji' => 'जी', 'jila' => 'जिला',
	'jile' => 'जिले', 'jio' => 'जिओ', 'jita' => 'जीता', 'jite' => 'जीते',
	'jivan' => 'जीवन', 'jivani' => 'जीवनी', 'jiwan' => 'जीवन', 'jo' => 'जो',
	'job' => 'जॉब', 'jodhpur' => 'जोधपुर', 'john' => 'जॉन', 'joshi' => 'जोशी',
	'jungle' => 'जंगल', 'jyada' => 'ज्यादा', 'jyoti' => 'ज्योति', 'k' => 'के',
	'ka' => 'का', 'kaal' => 'काल', 'kaam' => 'काम', 'kab' => 'कब', 'kabaddi' => 'कबड्डी',
	'kabir' => 'कबीर', 'kaha' => 'कहा', 'kahan' => 'कहाँ', 'kahani' => 'कहानी',
	'kahate' => 'कहते', 'kahte' => 'कहते', 'kailash' => 'कैलाश', 'kaisa' => 'कैसा',
	'kaise' => 'कैसे', 'kajal' => 'काजल', 'kal' => 'कल', 'kala' => 'कला',
	'kalam' => 'कलम', 'kali' => 'कली', 'kalidas' => 'कालिदास', 'kalyan' => 'कल्याण',
	'kam' => 'कम', 'kand' => 'कांड', 'kannada' => 'कनाडा', 'kanpur' => 'कानपुर',
	'kapoor' => 'कपूर', 'kar' => 'कर', 'karan' => 'कारण', 'kare' => 'करे',
	'karen' => 'करें', 'karn' => 'कर्ण', 'karna' => 'कर्ण', 'karnataka' => 'कर्नाटका',
	'karne' => 'करने', 'karni' => 'करनी', 'karta' => 'करता', 'karte' => 'करते',
	'karya' => 'कार्य', 'kashmir' => 'काश्मीर', 'kashyap' => 'कश्यप', 'katha' => 'कथा',
	'kaun' => 'कौन', 'kaur' => 'कौर', 'kavi' => 'कवि', 'kavita' => 'कविता',
	'kavya' => 'काव्या', 'kaya' => 'काया', 'ke' => 'के', 'kedarnath' => 'केदारनाथ',
	'kendra' => 'केंद्र', 'kese' => 'कैसे', 'kha' => 'खा', 'khalifa' => 'खलीफा',
	'khan' => 'खान', 'khana' => 'खाना', 'khane' => 'खाने', 'khanna' => 'खन्ना',
	'khatu' => 'खाटू', 'khel' => 'खेल', 'khesari' => 'खेसारी', 'kheti' => 'खेती',
	'kho' => 'खो', 'khoj' => 'खोज', 'ki' => 'की', 'kijiye' => 'कीजिये', 'kila' => 'किला',
	'kilometer' => 'किलोमीटर', 'kin' => 'किन', 'king' => 'किंग', 'kiran' => 'किरण',
	'kis' => 'किस', 'kisaan' => 'किसान', 'kisan' => 'किसान', 'kise' => 'किसे',
	'kish' => 'किश', 'kishan' => 'किशन', 'kishor' => 'किशोर', 'kishore' => 'किशोर',
	'kisi' => 'किसी', 'kiska' => 'किसका', 'kiske' => 'किसके', 'kiski' => 'किसकी',
	'kisko' => 'किसको', 'kisne' => 'किसने', 'kisse' => 'किस्से', 'kitana' => 'कितना',
	'kitane' => 'कितने', 'kitna' => 'कितना', 'kitne' => 'कितने', 'kiya' => 'किया',
	'kiye' => 'किए', 'ko' => 'को', 'kohli' => 'कोहली', 'koi' => 'कोई', 'kon' => 'कोण',
	'konsa' => 'कोनसा', 'konse' => 'कोनसे', 'konsi' => 'कोनसी', 'koun' => 'कौन',
	'kramank' => 'क्रमांक', 'kranti' => 'क्रांति', 'kre' => 'करे', 'krishi' => 'कृषि',
	'krishna' => 'कृष्ण', 'kriya' => 'क्रिया', 'kshetra' => 'क्षेत्र', 'kuch' => 'कुच',
	'kuchh' => 'कुछ', 'kul' => 'कुल', 'kuldeep' => 'कुलदीप', 'kumar' => 'कुमार',
	'kumari' => 'कुमारी', 'kya' => 'क्या', 'kyo' => 'क्यों', 'kyon' => 'क्यों',
	'kyu' => 'क्यों', 'la' => 'ल', 'labh' => 'लाभ', 'ladki' => 'लड़की', 'lagu' => 'लागू',
	'lake' => 'लेक', 'lakshmi' => 'लक्ष्मी', 'lal' => 'लाल', 'lalu' => 'लालू',
	'land' => 'लैंड', 'language' => 'लेंग्वेज', 'law' => 'लॉ', 'laxmi' => 'लक्ष्मी',
	'le' => 'ले', 'legislative' => 'लेजिस्लेटिव', 'lekh' => 'लेख', 'lekhan' => 'लेखन',
	'life' => 'लाइफ', 'light' => 'लाइट', 'likha' => 'लिखा', 'likhe' => 'लिखे',
	'likhen' => 'लिखें', 'likhiye' => 'लिखिए', 'limited' => 'लिमिटेड', 'line' => 'लाइन',
	'lines' => 'लाइंस', 'ling' => 'लिंग', 'link' => 'लिंक', 'lipi' => 'लिपि',
	'list' => 'लिस्ट', 'living' => 'लिविंग', 'liya' => 'लिया', 'liye' => 'लिए',
	'location' => 'लोकेशन', 'lock' => 'लॉक', 'log' => 'लॉग', 'lok' => 'लोक',
	'loksabha' => 'लोकसभा', 'loktantra' => 'लोकतंत्र', 'long' => 'लॉन्ग',
	'lord' => 'लॉर्ड', 'love' => 'लव', 'lucknow' => 'लखनऊ', 'lyrics' => 'लिरिक्स',
	'm' => 'एम', 'ma' => 'माँ', 'maa' => 'मां', 'machine' => 'मशीन', 'madan' => 'मदन',
	'madhav' => 'माधव', 'madhya' => 'मध्य', 'maha' => 'महा', 'mahabharat' => 'महाभारत',
	'mahadev' => 'महादेव', 'mahadevi' => 'महादेवी', 'mahakal' => 'महाकाल',
	'mahal' => 'महल', 'maharaj' => 'महाराज', 'maharaja' => 'महाराजा',
	'maharana' => 'महाराणा', 'maharashtra' => 'महाराष्ट्र', 'mahatma' => 'महात्मा',
	'mahatva' => 'महत्व', 'mahila' => 'महिला', 'mahiti' => 'माहिती', 'mai' => 'मई',
	'main' => 'मैं', 'maithili' => 'मैथिली', 'major' => 'मेजर', 'makar' => 'मकर',
	'make' => 'मेक', 'malik' => 'मालिक', 'man' => 'मन', 'mana' => 'मना',
	'management' => 'मैनेजमेंट', 'manav' => 'मानव', 'manchitra' => 'मानचित्र',
	'mandal' => 'मंडल', 'mandir' => 'मंदिर', 'mangal' => 'मंगल', 'manmarji' => 'मनमर्जी',
	'manoj' => 'मनोज', 'mantra' => 'मंत्र', 'mantri' => 'मंत्री', 'manu' => 'मनु',
	'many' => 'मान्य', 'map' => 'मैप', 'mara' => 'मरा', 'marathi' => 'मराठी',
	'march' => 'मार्च', 'mare' => 'मरे', 'market' => 'मार्केट', 'marriage' => 'मैरिज',
	'masjid' => 'मस्जिद', 'mata' => 'माता', 'mataram' => 'मातरम्', 'match' => 'मैच',
	'math' => 'मठ', 'mathura' => 'मथुरा', 'matka' => 'मटका', 'matlab' => 'मतलब',
	'matra' => 'मात्र', 'maurya' => 'मौर्या', 'max' => 'मैक्स', 'may' => 'मय',
	'me' => 'मि', 'meaning' => 'मीनिंग', 'medical' => 'मेडिकल', 'medium' => 'मीडियम',
	'meena' => 'मीणा', 'meera' => 'मीरा', 'mehta' => 'मेहता', 'mein' => 'में',
	'mela' => 'मेला', 'members' => 'मेंबर्स', 'men' => 'मेन', 'mera' => 'मेरा',
	'mere' => 'मेरे', 'meri' => 'मेरी', 'mia' => 'मिया', 'mil' => 'मिल', 'mila' => 'मिला',
	'mile' => 'मिले', 'mili' => 'मिली', 'minister' => 'मिनिस्टर', 'mishra' => 'मिश्रा',
	'mission' => 'मिशन', 'miya' => 'मिया', 'mla' => 'एमएलए', 'mobile' => 'मोबाइल',
	'model' => 'मॉडल', 'modi' => 'मोदी', 'mohammad' => 'मोहम्मद', 'mohan' => 'मोहन',
	'mohit' => 'मोहित', 'mother' => 'मदर', 'movement' => 'मूवमेंट', 'movi' => 'मोवी',
	'movie' => 'मूवी', 'movies' => 'मूवीज', 'mp' => 'एमपी', 'mp3' => 'एमपी३',
	'mp4' => 'एमपी४', 'mrutyu' => 'मृत्यु', 'ms' => 'एमएस', 'mudra' => 'मुद्रा',
	'mugal' => 'मुगल', 'muhammad' => 'मोहम्मद', 'mujhe' => 'मुझे', 'mukhya' => 'मुख्य',
	'mukhyamantri' => 'मुख्यमंत्री', 'mukhymantri' => 'मुख्यमंत्री', 'mul' => 'मूल',
	'mumbai' => 'मुंबई', 'munda' => 'मुंडा', 'murti' => 'मूर्ति', 'music' => 'म्युजिक',
	'muslim' => 'मुस्लिम', 'my' => 'माय', 'na' => 'ना', 'naam' => 'नाम', 'nadi' => 'नदी',
	'nadiya' => 'नाडिया', 'nagar' => 'नगर', 'nahi' => 'नहीं', 'nahin' => 'नहीं',
	'nai' => 'नई', 'naksha' => 'नक्शा', 'nalanda' => 'नालंदा', 'nam' => 'नम',
	'name' => 'नाम', 'nanak' => 'नानक', 'nand' => 'नंद', 'narayan' => 'नारायण',
	'narendra' => 'नरेंद्र', 'narmada' => 'नर्मदा', 'natak' => 'नाटक', 'nath' => 'नथ',
	'national' => 'नेशनल', 'nautanki' => 'नौटंकी', 'nda' => 'एनडीए', 'ne' => 'ने',
	'nehara' => 'नेहरा', 'nehra' => 'नेहरा', 'nehru' => 'नेहरू', 'nepal' => 'नेपाल',
	'neta' => 'नेता', 'network' => 'नेटवर्क', 'new' => 'न्यू', 'news' => 'न्यूज',
	'nibandh' => 'निबंध', 'nidhi' => 'निधि', 'nirman' => 'निर्माण',
	'nirvachan' => 'निर्वाचन', 'nishkarsh' => 'निष्कर्ष', 'nitin' => 'नितिन',
	'nitish' => 'नितीश', 'niyam' => 'नियम', 'niyantran' => 'नियंत्रण', 'no' => 'नो',
	'not' => 'नॉट', 'notanki' => 'नौटंकी', 'note' => 'नोट', 'notes' => 'नोट्स',
	'number' => 'नंबर', 'nuskhe' => 'नुस्खे', 'of' => 'ऑफ', 'off' => 'ऑफ',
	'office' => 'ऑफिस', 'oil' => 'ऑयल', 'old' => 'ओल्ड', 'om' => 'ॐ', 'on' => 'ऑन',
	'online' => 'ऑनलाइन', 'open' => 'ओपन', 'operation' => 'ऑपरेशन', 'or' => 'ओर',
	'order' => 'ऑर्डर', 'our' => 'आवर', 'pad' => 'पैड', 'pada' => 'पड़ा', 'page' => 'पेज',
	'pahla' => 'पहला', 'pahle' => 'पहले', 'pahli' => 'पहली', 'paisa' => 'पैसा',
	'pak' => 'पक', 'pakistan' => 'पाकिस्तान', 'pal' => 'पल', 'palace' => 'पैलेस',
	'pale' => 'पले', 'pan' => 'पान', 'panchayat' => 'पंचायत', 'pandey' => 'पांडे',
	'pandit' => 'पंडित', 'pani' => 'पानी', 'panipat' => 'पानीपत', 'paper' => 'पेपर',
	'par' => 'पर', 'parampara' => 'परंपरा', 'pardesh' => 'परदेश',
	'paribhasa' => 'परिभाषा', 'paribhasha' => 'परिभाषा', 'parichay' => 'परिचय',
	'pariksha' => 'परीक्षा', 'parikshan' => 'परीक्षण', 'parivar' => 'परिवार',
	'park' => 'पार्क', 'parkar' => 'प्रकार', 'parmanu' => 'परमाणु', 'part' => 'पार्ट',
	'party' => 'पार्टी', 'parvat' => 'पर्वत', 'pass' => 'पास', 'paswan' => 'पासवान',
	'patan' => 'पतन', 'patel' => 'पटेल', 'pati' => 'पति', 'patna' => 'पटना',
	'patni' => 'पटनी', 'patra' => 'पात्र', 'pawan' => 'पवन', 'pay' => 'पे',
	'pdf' => 'पीडीऍफ़', 'pe' => 'पे', 'ped' => 'पेड़', 'people' => 'पीपल', 'per' => 'पैर',
	'phone' => 'फोन', 'photo' => 'फोटो', 'photos' => 'फोटोज', 'pic' => 'पिछ',
	'picture' => 'पिक्चर', 'pita' => 'पिता', 'place' => 'प्लेस', 'places' => 'प्लेसिस',
	'plan' => 'प्लान', 'plant' => 'प्लांट', 'play' => 'प्ले', 'point' => 'पॉइंट',
	'police' => 'पुलिस', 'political' => 'पोलिटिकल', 'pooja' => 'पूजा',
	'population' => 'पॉपुलेशन', 'post' => 'पोस्ट', 'praan' => 'प्राण',
	'prabhav' => 'प्रभाव', 'prachin' => 'प्राचीन', 'pradesh' => 'प्रदेश',
	'pradhan' => 'प्रधान', 'pradhanmantri' => 'प्रधानमंत्री', 'pradushan' => 'प्रदूषण',
	'prakar' => 'प्रकार', 'prakash' => 'प्रकाश', 'prakriya' => 'प्रक्रिया',
	'pramukh' => 'प्रमुख', 'pran' => 'प्राण', 'prasad' => 'प्रसाद',
	'prashant' => 'प्रशांत', 'pratap' => 'प्रताप', 'pratham' => 'प्रथम',
	'prem' => 'प्रेम', 'premchand' => 'प्रेमचंद', 'present' => 'प्रेजेंट',
	'president' => 'प्रेजिडेंट', 'price' => 'प्राइस', 'prithvi' => 'पृथ्वी',
	'prithviraj' => 'पृथ्वीराज', 'process' => 'प्रोसेस', 'products' => 'प्रॉडक्ट्स',
	'project' => 'प्रोजेक्ट', 'proto' => 'प्रोटो', 'public' => 'पब्लिक', 'puja' => 'पूजा',
	'punjab' => 'पंजाब', 'pura' => 'पुरा', 'puran' => 'पुराण', 'purana' => 'पुराना',
	'purani' => 'पुरानी', 'puraskar' => 'पुरस्कर', 'puri' => 'पुरी',
	'purskar' => 'पुरस्कर', 'purv' => 'पूर्व', 'putra' => 'पुत्र', 'pyar' => 'प्यार',
	'question' => 'क्वेश्चन', 'raag' => 'राग', 'rachna' => 'रचना', 'radha' => 'राधा',
	'raha' => 'रहा', 'rahe' => 'रहे', 'rahi' => 'रही', 'rahul' => 'राहुल', 'rai' => 'राई',
	'rail' => 'रेल', 'railway' => 'रेलवे', 'raipur' => 'रायपुर', 'raj' => 'राज',
	'raja' => 'राजा', 'rajasthan' => 'राजस्थान', 'rajdhani' => 'राजधानी',
	'rajendra' => 'राजेंद्र', 'rajesh' => 'राजेश', 'rajiv' => 'राजीव',
	'rajkumar' => 'राजकुमार', 'rajniti' => 'राजनीति', 'rajnitik' => 'राजनितिक',
	'rajput' => 'राजपुत', 'rajsthan' => 'राजस्थान', 'rajy' => 'राज्य', 'rajya' => 'राज्य',
	'rajyapal' => 'राज्यपाल', 'rakhi' => 'राखी', 'ram' => 'राम', 'raman' => 'रमन',
	'ramayan' => 'रामायण', 'rana' => 'राणा', 'rani' => 'रानी', 'rao' => 'राउ',
	'rape' => 'रपे', 'ras' => 'रस', 'rashi' => 'राशी', 'rashtra' => 'राष्ट्र',
	'rashtrapati' => 'राष्ट्रपति', 'rashtriy' => 'राष्ट्रिय', 'rashtriya' => 'राष्ट्रिय',
	'ratan' => 'रतन', 'rate' => 'रेट', 'ravan' => 'रावण', 'ravi' => 'रवि',
	'ravindra' => 'रवींद्र', 'ray' => 'राय', 'real' => 'रियल', 'red' => 'रेड',
	'rekha' => 'रेखा', 'religion' => 'रिलिजन', 'report' => 'रिपोर्ट',
	'research' => 'रिसर्च', 'result' => 'रिजल्ट', 'rishi' => 'ऋषि', 'river' => 'रिवर',
	'road' => 'रोड', 'rohit' => 'रोहित', 'role' => 'रोल', 'roman' => 'रोमन',
	'roop' => 'रूप', 'round' => 'राउंड', 'rounds' => 'राउंड्स', 'roy' => 'राॅय',
	'rss' => 'आरएसएस', 'sa' => 'सा', 'saal' => 'साल', 'sab' => 'सब', 'sabha' => 'सभा',
	'sabhi' => 'सभी', 'sabhyata' => 'सभ्यता', 'sabse' => 'सबसे', 'sach' => 'सच',
	'sadi' => 'सड़ी', 'sagar' => 'सागर', 'sahab' => 'सहाब', 'sahi' => 'साही',
	'sahib' => 'साहिब', 'sahit' => 'सहित', 'sahitya' => 'साहित्य', 'saint' => 'सैंट',
	'sakta' => 'सकता', 'sakte' => 'सकते', 'sakti' => 'सकती', 'sal' => 'साल',
	'salary' => 'सैलरी', 'salman' => 'सलमान', 'samachar' => 'समाचार', 'samaj' => 'समाज',
	'samajhte' => 'समझते', 'samajik' => 'सामाजिक', 'saman' => 'समन', 'samay' => 'समय',
	'sambandh' => 'संबंध', 'sambandhit' => 'संबंधित', 'samjhaie' => 'समझाइए',
	'samman' => 'सम्मान', 'sampurn' => 'सम्पूर्ण', 'samrajya' => 'साम्राज्य',
	'samrat' => 'सम्राट', 'samvidhan' => 'संविधान', 'san' => 'सन', 'sanchar' => 'संचार',
	'sandhi' => 'संधि', 'sangathan' => 'संगठन', 'sangh' => 'संघ', 'sani' => 'सनी',
	'sanjay' => 'संजय', 'sankhya' => 'संख्या', 'sanrachna' => 'संरचना',
	'sansad' => 'संसद', 'sanskrit' => 'संस्कृत', 'sanskriti' => 'संस्कृति',
	'sant' => 'संत', 'sanvidhan' => 'संविधान', 'sar' => 'एसएआर', 'sardar' => 'सरदार',
	'sare' => 'सरे', 'sareaam' => 'सरेआम', 'sarkar' => 'सर्कार', 'sarkari' => 'सरकारी',
	'sath' => 'साथ', 'satish' => 'सतीश', 'satta' => 'सट्टा', 'satya' => 'सत्य',
	'savidhan' => 'सविधान', 'sc' => 'एससी', 'school' => 'स्कूल', 'science' => 'साइंस',
	'se' => 'से', 'season' => 'सीज़न', 'seat' => 'सीट', 'second' => 'सेकंड',
	'security' => 'सिक्युरिटी', 'seema' => 'सीमा', 'sem' => 'सेम',
	'semester' => 'सेमेस्टर', 'sena' => 'सेना', 'serial' => 'सीरियल', 'series' => 'सिरीज',
	'seva' => 'सेवा', 'sha' => 'श', 'shaadi' => 'शादी', 'shabd' => 'शब्द',
	'shadi' => 'शादी', 'shah' => 'शाह', 'shakti' => 'शक्ति', 'shankar' => 'शंकर',
	'share' => 'शेयर', 'sharma' => 'शर्मा', 'shastra' => 'शास्त्र',
	'shastri' => 'शास्त्री', 'sheet' => 'शीट', 'shekhar' => 'शेखर', 'shiksha' => 'शिक्षा',
	'shikshan' => 'शिक्षण', 'shiv' => 'शिव', 'shiva' => 'शिवा', 'shivaji' => 'शिवाजी',
	'short' => 'शार्ट', 'shree' => 'श्री', 'shri' => 'श्री', 'shukla' => 'शुक्ला',
	'shyam' => 'श्याम', 'si' => 'सी', 'siddhant' => 'सिद्धांत', 'side' => 'साइड',
	'sidhu' => 'सिद्धू', 'sikandar' => 'सिकंदर', 'sikh' => 'सिक्ख', 'sikkim' => 'सिक्किम',
	'sindhu' => 'सिंधु', 'sing' => 'सींग', 'singer' => 'सिंगर', 'singh' => 'सिंह',
	'sinha' => 'सिन्हा', 'sir' => 'सर', 'sit' => 'सित', 'size' => 'साइज',
	'society' => 'सोसाइटी', 'solar' => 'सोलर', 'son' => 'सोन', 'song' => 'सांग',
	'sonu' => 'सोनू', 'sooraj' => 'सुरज', 'south' => 'साउथ', 'space' => 'स्पेस',
	'speech' => 'स्पीच', 'sports' => 'स्पोर्ट्स', 'sri' => 'श्री', 'st' => 'एसटी',
	'star' => 'स्टार', 'state' => 'स्टेट', 'station' => 'स्टेशन', 'sthal' => 'स्थल',
	'sthan' => 'स्थान', 'sthapna' => 'स्थापना', 'story' => 'स्टोरी', 'study' => 'स्टडी',
	'subhash' => 'सुभाष', 'subject' => 'सब्जेक्ट', 'suchi' => 'सूची',
	'sultan' => 'सुल्तान', 'sun' => 'सन', 'sunil' => 'सुनील', 'sunny' => 'सनी',
	'super' => 'सुपर', 'suraj' => 'सूरज', 'surdas' => 'सूरदास', 'surya' => 'सूर्य',
	'suryakant' => 'सूर्यकांत', 'sutra' => 'सूत्र', 'swami' => 'स्वामी',
	'swaroop' => 'स्वरूप', 'swatantrata' => 'स्वतंत्रता', 'system' => 'सिस्टम',
	'ta' => 'ता', 'table' => 'टेबल', 'tagore' => 'टैगोर', 'tahsil' => 'तहसील',
	'taj' => 'ताज', 'tak' => 'तक', 'tarika' => 'तरीका', 'tasting' => 'टेस्टिंग',
	'tata' => 'ताता', 'tatha' => 'तथा', 'tatv' => 'तत्व', 'tax' => 'टैक्स',
	'team' => 'टीम', 'technology' => 'टेक्नोलॉजी', 'tel' => 'तेल', 'temple' => 'टेम्पल',
	'tere' => 'तेरे', 'teri' => 'तेरी', 'testing' => 'टेस्टिंग', 'tha' => 'था',
	'thakur' => 'ठाकुर', 'thana' => 'थाना', 'that' => 'दैट', 'the' => 'थे',
	'theory' => 'थिअरी', 'thi' => 'थी', 'tiger' => 'टाइगर', 'time' => 'टाइम',
	'tippani' => 'टिप्पणी', 'tips' => 'टिप्स', 'tiwari' => 'तिवारी', 'to' => 'टू',
	'today' => 'टुडे', 'top' => 'टॉप', 'topic' => 'टॉपिक', 'total' => 'टोटल',
	'trading' => 'ट्रेडिंग', 'train' => 'ट्रेन', 'translate' => 'ट्रांसलेट',
	'tripathi' => 'त्रिपाठी', 'tu' => 'तु', 'tulsi' => 'तुलसी', 'tulsidas' => 'तुलसीदास',
	'tum' => 'तुम', 'tv' => 'टीवी', 'type' => 'टाइप', 'types' => 'टाइप्स',
	'udaharan' => 'उदाहरण', 'udaipur' => 'उदयपुर', 'uday' => 'उदय',
	'uddeshy' => 'उद्देश्य', 'ujjain' => 'उज्जैन', 'umar' => 'उमर',
	'university' => 'यूनिवर्सिटी', 'unka' => 'उनका', 'unke' => 'उनके', 'unki' => 'उनकी',
	'unnao' => 'उन्नाव', 'up' => 'उप', 'upar' => 'ऊपर', 'upay' => 'उपाय',
	'upsc' => 'यूपीएससी', 'upyog' => 'उपयोग', 'urdu' => 'उर्दू', 'use' => 'उसे',
	'uska' => 'उसका', 'uske' => 'उसके', 'utpati' => 'उत्पत्ति', 'utpatti' => 'उत्पत्ति',
	'uttar' => 'उत्तर', 'uttarakhand' => 'उत्तराखंड', 'vaidik' => 'वैदिक',
	'vale' => 'वाले', 'valmiki' => 'वाल्मिकी', 'van' => 'वैन', 'vande' => 'वंदे',
	'vansh' => 'वंश', 'varanasi' => 'वाराणसी', 'varma' => 'वर्मा', 'varnan' => 'वर्णन',
	'varsh' => 'वर्ष', 'vartman' => 'वर्तमान', 'vayu' => 'वायु', 'ved' => 'वेद',
	'veer' => 'वीर', 'vellur' => 'वेल्लूर', 'velur' => 'वेल्लूर', 'verma' => 'वर्मा',
	'vibhinn' => 'विभिन्न', 'vichar' => 'विचार', 'video' => 'वीडियो', 'videsh' => 'विदेश',
	'vidhan' => 'विधान', 'vidhansabha' => 'विधानसभा', 'vidhayak' => 'विधायक',
	'vidhi' => 'विधि', 'vidroh' => 'विद्रोह', 'vigyan' => 'विज्ञानं', 'vijay' => 'विजय',
	'vikas' => 'विकास', 'vikash' => 'विकाश', 'vikram' => 'विक्रम', 'village' => 'विलेज',
	'vinod' => 'विनोद', 'viral' => 'वायरल', 'virat' => 'विराट', 'vishanu' => 'विष्णु',
	'visheshtaen' => 'विशेषताएं', 'vishnu' => 'विष्णु', 'vishva' => 'विश्व',
	'vistar' => 'विस्तार', 'vitamin' => 'विटामिन', 'vivah' => 'विवाह',
	'vivekanand' => 'विवेकानंद', 'voice' => 'वॉयस', 'vote' => 'वोट', 'voter' => 'वोटर',
	'voting' => 'वोटिंग', 'vs' => 'वस', 'vyakhya' => 'व्याख्या', 'vyas' => 'व्यास',
	'vyavastha' => 'व्यवस्था', 'wala' => 'वाला', 'wale' => 'वाले', 'wali' => 'वाली',
	'war' => 'वॉर', 'ward' => 'वार्ड', 'was' => 'वास', 'water' => 'वाटर', 'web' => 'वेब',
	'what' => 'व्हाट', 'whatsapp' => 'व्हाट्सएप', 'when' => 'व्हेन', 'white' => 'वाइट',
	'wife' => 'वाइफ', 'wiki' => 'विकी', 'wikipedia' => 'विकिपीडिया', 'with' => 'विद',
	'women' => 'वीमेन', 'word' => 'वर्ड', 'words' => 'वर्ड्स', 'work' => 'वर्क',
	'world' => 'वर्ल्ड', 'write' => 'राइट', 'ya' => 'या', 'yadav' => 'यादव',
	'yah' => 'यह', 'yatra' => 'यात्रा', 'ye' => 'ये', 'year' => 'ईयर', 'yog' => 'योग',
	'yoga' => 'योग', 'yogdan' => 'योगदान', 'yogi' => 'योगी', 'yojana' => 'योजना',
	'yojna' => 'योजना', 'you' => 'यू', 'youtube' => 'यूट्यूब', 'yuddh' => 'युद्ध',
	'yudh' => 'युद्ध', 'yug' => 'युग',
	];
